apiVersion: v1
kind: Secret
metadata:
  name: pm-backend-secrets
  namespace: enterprise-pm
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "pm_user"
  SPRING_DATASOURCE_PASSWORD: "pm_password_prod_secure_9988"
  JWT_SECRET: "enterprise_pm_super_secret_jwt_key_that_is_at_least_32_bytes_long_12345"
